# Generated by Django 3.1.4 on 2021-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(to='auctions.Comment'),
        ),
    ]
