# Generated by Django 3.1.4 on 2021-02-18 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
