# Generated by Django 3.1.4 on 2021-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('n', 'none'), ('f', 'food'), ('e', 'electronics'), ('c', 'clothes')], default='category', max_length=1),
        ),
    ]
